# Generated by Django 4.0 on 2022-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
