# Generated by Django 4.0 on 2022-01-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('c_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
    ]
