# Generated by Django 4.0 on 2022-01-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_exchange1_delete_exchange'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exchange1',
            new_name='Exchange',
        ),
    ]
