# Generated by Django 4.0 on 2022-01-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
