# Generated by Django 4.0 on 2022-01-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_products_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(default='product.jpg', upload_to='products'),
        ),
    ]
