# Generated by Django 4.0 on 2022-01-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
