# Generated by Django 4.0 on 2022-01-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_products_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
