# Generated by Django 4.0 on 2022-01-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_alter_products_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Products1',
        ),
    ]
